/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ResponseWithMessage } from '../models';
// @ts-ignore
import type { VerificationEmailDto } from '../models';
/**
 * EmailApi - axios parameter creator
 * @export
 */
export const EmailApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Send verification email
         * @param {VerificationEmailDto} verificationEmailDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailControllerSendVerificationEmail: async (verificationEmailDto: VerificationEmailDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verificationEmailDto' is not null or undefined
            assertParamExists('emailControllerSendVerificationEmail', 'verificationEmailDto', verificationEmailDto)
            const localVarPath = `/api/email/send-verification`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verificationEmailDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmailApi - functional programming interface
 * @export
 */
export const EmailApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmailApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Send verification email
         * @param {VerificationEmailDto} verificationEmailDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async emailControllerSendVerificationEmail(verificationEmailDto: VerificationEmailDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseWithMessage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.emailControllerSendVerificationEmail(verificationEmailDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmailApi.emailControllerSendVerificationEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EmailApi - factory interface
 * @export
 */
export const EmailApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmailApiFp(configuration)
    return {
        /**
         * 
         * @summary Send verification email
         * @param {EmailApiEmailControllerSendVerificationEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        emailControllerSendVerificationEmail(requestParameters: EmailApiEmailControllerSendVerificationEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResponseWithMessage> {
            return localVarFp.emailControllerSendVerificationEmail(requestParameters.verificationEmailDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for emailControllerSendVerificationEmail operation in EmailApi.
 * @export
 * @interface EmailApiEmailControllerSendVerificationEmailRequest
 */
export interface EmailApiEmailControllerSendVerificationEmailRequest {
    /**
     * 
     * @type {VerificationEmailDto}
     * @memberof EmailApiEmailControllerSendVerificationEmail
     */
    readonly verificationEmailDto: VerificationEmailDto
}

/**
 * EmailApi - object-oriented interface
 * @export
 * @class EmailApi
 * @extends {BaseAPI}
 */
export class EmailApi extends BaseAPI {
    /**
     * 
     * @summary Send verification email
     * @param {EmailApiEmailControllerSendVerificationEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmailApi
     */
    public emailControllerSendVerificationEmail(requestParameters: EmailApiEmailControllerSendVerificationEmailRequest, options?: RawAxiosRequestConfig) {
        return EmailApiFp(this.configuration).emailControllerSendVerificationEmail(requestParameters.verificationEmailDto, options).then((request) => request(this.axios, this.basePath));
    }
}

