/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TranslationData } from './translation-data';

/**
 * 
 * @export
 * @interface AddTranslationDto
 */
export interface AddTranslationDto {
    /**
     * The language code for the translations
     * @type {string}
     * @memberof AddTranslationDto
     */
    'language': string;
    /**
     * Array of translations to add
     * @type {Array<TranslationData>}
     * @memberof AddTranslationDto
     */
    'data': Array<TranslationData>;
}

