/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';
// May contain unused imports in some cases
// @ts-ignore
import type { ProvinceTranslationsInner } from './province-translations-inner';

/**
 * 
 * @export
 * @interface Amenity
 */
export interface Amenity {
    /**
     * 
     * @type {string}
     * @memberof Amenity
     */
    'id': string;
    /**
     * Soft delete flag
     * @type {boolean}
     * @memberof Amenity
     */
    'isDeleted': boolean;
    /**
     * Soft delete timestamp
     * @type {string}
     * @memberof Amenity
     */
    'deletedAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof Amenity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Amenity
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof Amenity
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Amenity
     */
    'slug': string;
    /**
     * Icon image for the amenity
     * @type {Image}
     * @memberof Amenity
     */
    'icon': Image | null;
    /**
     * 
     * @type {string}
     * @memberof Amenity
     */
    'type': AmenityTypeEnum;
    /**
     * List of translations for the amenity
     * @type {Array<ProvinceTranslationsInner>}
     * @memberof Amenity
     */
    'translations': Array<ProvinceTranslationsInner>;
}

/**
    * @export
    * @enum {string}
    */
export enum AmenityTypeEnum {
    Room = 'ROOM',
    Property = 'PROPERTY',
    Service = 'SERVICE'
}


