/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BranchTranslationsInner } from './branch-translations-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';
// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';
// May contain unused imports in some cases
// @ts-ignore
import type { Province } from './province';

/**
 * 
 * @export
 * @interface Branch
 */
export interface Branch {
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    'id': string;
    /**
     * Soft delete flag
     * @type {boolean}
     * @memberof Branch
     */
    'isDeleted': boolean;
    /**
     * Soft delete timestamp
     * @type {string}
     * @memberof Branch
     */
    'deletedAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    'updatedAt': string;
    /**
     * ID of the province where this branch is located
     * @type {string}
     * @memberof Branch
     */
    'provinceId': string;
    /**
     * Province where this branch is located
     * @type {Province}
     * @memberof Branch
     */
    'province': Province;
    /**
     * Branch\'s thumbnail image
     * @type {Image}
     * @memberof Branch
     */
    'thumbnail': Image;
    /**
     * Branch\'s image gallery
     * @type {Array<Image>}
     * @memberof Branch
     */
    'images': Array<Image>;
    /**
     * Branch\'s name
     * @type {string}
     * @memberof Branch
     */
    'name': string;
    /**
     * Branch\'s slug
     * @type {string}
     * @memberof Branch
     */
    'slug': string;
    /**
     * Branch\'s description
     * @type {string}
     * @memberof Branch
     */
    'description': string;
    /**
     * Branch\'s contact phone number
     * @type {string}
     * @memberof Branch
     */
    'phone': string;
    /**
     * Branch\'s active status
     * @type {boolean}
     * @memberof Branch
     */
    'is_active': boolean;
    /**
     * Branch\'s physical address
     * @type {string}
     * @memberof Branch
     */
    'address': string;
    /**
     * Branch\'s rating
     * @type {number}
     * @memberof Branch
     */
    'rating': number;
    /**
     * List of translations for the branch
     * @type {Array<BranchTranslationsInner>}
     * @memberof Branch
     */
    'translations': Array<BranchTranslationsInner>;
    /**
     * List of available languages for this branch
     * @type {Array<string>}
     * @memberof Branch
     */
    'availableLanguages': Array<BranchAvailableLanguagesEnum>;
    /**
     * Branch\'s geographical location
     * @type {Location}
     * @memberof Branch
     */
    'location'?: Location;
}

/**
    * @export
    * @enum {string}
    */
export enum BranchAvailableLanguagesEnum {
    En = 'EN',
    Vi = 'VI'
}


