/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfirmPaymentWebhookDto
 */
export interface ConfirmPaymentWebhookDto {
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentWebhookDto
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentWebhookDto
     */
    'desc': string;
    /**
     * 
     * @type {object}
     * @memberof ConfirmPaymentWebhookDto
     */
    'data': object;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPaymentWebhookDto
     */
    'signature': string;
}

