/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoomPriceHistoryTranslationDto } from './room-price-history-translation-dto';

/**
 * 
 * @export
 * @interface CreateRoomPriceHistoryDto
 */
export interface CreateRoomPriceHistoryDto {
    /**
     * Day that the price is applied
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'name': string;
    /**
     * ID of the room detail
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'roomDetailId': string;
    /**
     * Effective from date
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'effective_from': string;
    /**
     * Description of the price history
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'description'?: string;
    /**
     * Hotel Room\'s base price per hour
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'price_per_hour'?: string;
    /**
     * Hotel Room\'s base price per day
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'price_per_day'?: string;
    /**
     * Hotel Room\'s base price per night
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'price_per_night'?: string;
    /**
     * Effective to date
     * @type {string}
     * @memberof CreateRoomPriceHistoryDto
     */
    'effective_to'?: string;
    /**
     * Translations for the price history
     * @type {Array<RoomPriceHistoryTranslationDto>}
     * @memberof CreateRoomPriceHistoryDto
     */
    'translations'?: Array<RoomPriceHistoryTranslationDto>;
}

