/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProvinceTranslationDto } from './province-translation-dto';

/**
 * 
 * @export
 * @interface CreateProvinceDto
 */
export interface CreateProvinceDto {
    /**
     * Name of the province
     * @type {string}
     * @memberof CreateProvinceDto
     */
    'name': string;
    /**
     * ZIP/Postal code of the province
     * @type {string}
     * @memberof CreateProvinceDto
     */
    'zip_code': string;
    /**
     * URL-friendly slug of the province name
     * @type {string}
     * @memberof CreateProvinceDto
     */
    'slug': string;
    /**
     * Translations for the province
     * @type {Array<ProvinceTranslationDto>}
     * @memberof CreateProvinceDto
     */
    'translations'?: Array<ProvinceTranslationDto>;
}

