/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BranchTranslationDto } from './branch-translation-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';

/**
 * 
 * @export
 * @interface CreateBranchDto
 */
export interface CreateBranchDto {
    /**
     * ID of the province where this branch is located
     * @type {string}
     * @memberof CreateBranchDto
     */
    'provinceId': string;
    /**
     * The branch\'s thumbnail image.
     * @type {Image}
     * @memberof CreateBranchDto
     */
    'thumbnail': Image;
    /**
     * The branch\'s images.
     * @type {Array<Image>}
     * @memberof CreateBranchDto
     */
    'images': Array<Image>;
    /**
     * The branch\'s name.
     * @type {string}
     * @memberof CreateBranchDto
     */
    'name': string;
    /**
     * The branch\'s slug.
     * @type {string}
     * @memberof CreateBranchDto
     */
    'slug': string;
    /**
     * The branch\'s description.
     * @type {string}
     * @memberof CreateBranchDto
     */
    'description': string;
    /**
     * The branch\'s phone number.
     * @type {string}
     * @memberof CreateBranchDto
     */
    'phone': string;
    /**
     * The branch\'s active status.
     * @type {boolean}
     * @memberof CreateBranchDto
     */
    'is_active': boolean;
    /**
     * The branch\'s address.
     * @type {string}
     * @memberof CreateBranchDto
     */
    'address': string;
    /**
     * The branch\'s rating.
     * @type {number}
     * @memberof CreateBranchDto
     */
    'rating': number;
    /**
     * Translations for the branch
     * @type {Array<BranchTranslationDto>}
     * @memberof CreateBranchDto
     */
    'translations'?: Array<BranchTranslationDto>;
}

