/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GuestDetail } from './guest-detail';

/**
 * 
 * @export
 * @interface CreateBookingOnlineDto
 */
export interface CreateBookingOnlineDto {
    /**
     * Booking type
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'type': CreateBookingOnlineDtoTypeEnum;
    /**
     * Start date of the booking
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'start_date': string;
    /**
     * End date of the booking
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'end_date': string;
    /**
     * Start time of the booking
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'start_time': string;
    /**
     * End time of the booking
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'end_time': string;
    /**
     * Number of guests
     * @type {number}
     * @memberof CreateBookingOnlineDto
     */
    'number_of_guests': number;
    /**
     * Number of adults
     * @type {number}
     * @memberof CreateBookingOnlineDto
     */
    'adults': number;
    /**
     * Number of children
     * @type {number}
     * @memberof CreateBookingOnlineDto
     */
    'children': number;
    /**
     * Number of infants
     * @type {number}
     * @memberof CreateBookingOnlineDto
     */
    'infants': number;
    /**
     * ID of the room detail being booked
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'detailId': string;
    /**
     * Name of the guest
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'name'?: string;
    /**
     * Phone number of the guest
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'phone'?: string;
    /**
     * Special requirements
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'special_requests'?: string;
    /**
     * Guest details
     * @type {GuestDetail}
     * @memberof CreateBookingOnlineDto
     */
    'guest_details'?: GuestDetail;
    /**
     * Promotion code
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'promotion_code'?: string;
    /**
     * Payment method
     * @type {string}
     * @memberof CreateBookingOnlineDto
     */
    'payment_method'?: CreateBookingOnlineDtoPaymentMethodEnum;
    /**
     * Is this booking a business trip?
     * @type {boolean}
     * @memberof CreateBookingOnlineDto
     */
    'is_business_trip'?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateBookingOnlineDtoTypeEnum {
    Hourly = 'HOURLY',
    Nightly = 'NIGHTLY',
    Daily = 'DAILY'
}
/**
    * @export
    * @enum {string}
    */
export enum CreateBookingOnlineDtoPaymentMethodEnum {
    Cash = 'CASH',
    Banking = 'BANKING',
    Zalopay = 'ZALOPAY',
    Momo = 'MOMO',
    VnPay = 'VN_PAY',
    VietQr = 'VIET_QR'
}


