/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmailHealthResponseDto
 */
export interface EmailHealthResponseDto {
    /**
     * Health status of the email service
     * @type {string}
     * @memberof EmailHealthResponseDto
     */
    'status': EmailHealthResponseDtoStatusEnum;
    /**
     * Whether SMTP connection is active
     * @type {boolean}
     * @memberof EmailHealthResponseDto
     */
    'smtp': boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum EmailHealthResponseDtoStatusEnum {
    Healthy = 'healthy',
    Unhealthy = 'unhealthy'
}


