/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthErrorMessageEnum } from './auth-error-message-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { BookingErrorMessagesEnum } from './booking-error-messages-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { CommonErrorMessagesEnum } from './common-error-messages-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { ImageErrorMessagesEnum } from './image-error-messages-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RoleErrorMessagesEnum } from './role-error-messages-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { RoomErrorMessagesEnum } from './room-error-messages-enum';
// May contain unused imports in some cases
// @ts-ignore
import type { SortCaseEnum } from './sort-case-enum';

/**
 * 
 * @export
 * @interface ExposedEnumsDto
 */
export interface ExposedEnumsDto {
    /**
     * 
     * @type {SortCaseEnum}
     * @memberof ExposedEnumsDto
     */
    'sortCase': SortCaseEnum;
    /**
     * 
     * @type {CommonErrorMessagesEnum}
     * @memberof ExposedEnumsDto
     */
    'commonErrorMessages': CommonErrorMessagesEnum;
    /**
     * 
     * @type {RoleErrorMessagesEnum}
     * @memberof ExposedEnumsDto
     */
    'roleErrorMessages': RoleErrorMessagesEnum;
    /**
     * 
     * @type {AuthErrorMessageEnum}
     * @memberof ExposedEnumsDto
     */
    'authErrorMessage': AuthErrorMessageEnum;
    /**
     * 
     * @type {ImageErrorMessagesEnum}
     * @memberof ExposedEnumsDto
     */
    'imageErrorMessages': ImageErrorMessagesEnum;
    /**
     * 
     * @type {RoomErrorMessagesEnum}
     * @memberof ExposedEnumsDto
     */
    'roomErrorMessages': RoomErrorMessagesEnum;
    /**
     * 
     * @type {BookingErrorMessagesEnum}
     * @memberof ExposedEnumsDto
     */
    'bookingErrorMessages': BookingErrorMessagesEnum;
}



