/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterBranchesDto
 */
export interface FilterBranchesDto {
    /**
     * Search by keyword
     * @type {string}
     * @memberof FilterBranchesDto
     */
    'keyword'?: string;
    /**
     * Filter by active status
     * @type {boolean}
     * @memberof FilterBranchesDto
     */
    'is_active'?: boolean;
    /**
     * Filter by rating
     * @type {number}
     * @memberof FilterBranchesDto
     */
    'rating'?: number;
    /**
     * Filter by province
     * @type {string}
     * @memberof FilterBranchesDto
     */
    'provinceId'?: string;
    /**
     * Filter by province slug
     * @type {string}
     * @memberof FilterBranchesDto
     */
    'provinceSlug'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof FilterBranchesDto
     */
    'amenities'?: Array<string>;
}

