/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilterBookingsDto
 */
export interface FilterBookingsDto {
    /**
     * Filter by booking status
     * @type {Array<string>}
     * @memberof FilterBookingsDto
     */
    'status'?: Array<FilterBookingsDtoStatusEnum>;
    /**
     * Filter by booking type
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'type'?: FilterBookingsDtoTypeEnum;
    /**
     * Search by keyword
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'keyword'?: string;
    /**
     * Filter by branch
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'branchId'?: string;
    /**
     * Filter by user
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'userId'?: string;
    /**
     * Filter by room detail
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'detailId'?: string;
    /**
     * Filter by room
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'roomId'?: string;
    /**
     * Filter by start date
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'start_date'?: string;
    /**
     * Filter by end date
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'end_date'?: string;
    /**
     * Filter by payment status
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'payment_status'?: FilterBookingsDtoPaymentStatusEnum;
    /**
     * Filter by payment method
     * @type {string}
     * @memberof FilterBookingsDto
     */
    'payment_method'?: FilterBookingsDtoPaymentMethodEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FilterBookingsDtoStatusEnum {
    Pending = 'PENDING',
    WaitingForCheckIn = 'WAITING_FOR_CHECK_IN',
    CheckedIn = 'CHECKED_IN',
    Cancelled = 'CANCELLED',
    Completed = 'COMPLETED',
    Refunded = 'REFUNDED',
    Rejected = 'REJECTED'
}
/**
    * @export
    * @enum {string}
    */
export enum FilterBookingsDtoTypeEnum {
    Hourly = 'HOURLY',
    Nightly = 'NIGHTLY',
    Daily = 'DAILY'
}
/**
    * @export
    * @enum {string}
    */
export enum FilterBookingsDtoPaymentStatusEnum {
    Unpaid = 'UNPAID',
    Paid = 'PAID',
    Failed = 'FAILED',
    Refunded = 'REFUNDED'
}
/**
    * @export
    * @enum {string}
    */
export enum FilterBookingsDtoPaymentMethodEnum {
    Cash = 'CASH',
    Banking = 'BANKING',
    Zalopay = 'ZALOPAY',
    Momo = 'MOMO',
    VnPay = 'VN_PAY',
    VietQr = 'VIET_QR'
}


