/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAnalyticsQueryDto
 */
export interface GetAnalyticsQueryDto {
    /**
     * Branch ID to get analytics for
     * @type {string}
     * @memberof GetAnalyticsQueryDto
     */
    'branchId'?: string;
    /**
     * Start date for analytics (YYYY-MM-DD)
     * @type {string}
     * @memberof GetAnalyticsQueryDto
     */
    'startDate'?: string;
    /**
     * End date for analytics (YYYY-MM-DD)
     * @type {string}
     * @memberof GetAnalyticsQueryDto
     */
    'endDate'?: string;
    /**
     * Period type for analytics
     * @type {string}
     * @memberof GetAnalyticsQueryDto
     */
    'periodType'?: GetAnalyticsQueryDtoPeriodTypeEnum;
    /**
     * Number of months to analyze
     * @type {number}
     * @memberof GetAnalyticsQueryDto
     */
    'months'?: number;
}

/**
    * @export
    * @enum {string}
    */
export enum GetAnalyticsQueryDtoPeriodTypeEnum {
    Daily = 'DAILY',
    Monthly = 'MONTHLY',
    Yearly = 'YEARLY'
}


