/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';

/**
 * 
 * @export
 * @interface GuestDetail
 */
export interface GuestDetail {
    /**
     * Guest identification number
     * @type {string}
     * @memberof GuestDetail
     */
    'identification_number': string;
    /**
     * Guest identification card type
     * @type {string}
     * @memberof GuestDetail
     */
    'identification_card': GuestDetailIdentificationCardEnum;
    /**
     * Front image of the guest identification card
     * @type {Image}
     * @memberof GuestDetail
     */
    'front_image': Image;
    /**
     * Back image of the guest identification card
     * @type {Image}
     * @memberof GuestDetail
     */
    'back_image': Image;
}

/**
    * @export
    * @enum {string}
    */
export enum GuestDetailIdentificationCardEnum {
    Cccd = 'CCCD',
    Cmnd = 'CMND',
    Cmt = 'CMT'
}


