/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HotelRoomTranslationDto
 */
export interface HotelRoomTranslationDto {
    /**
     * Language of the translation
     * @type {string}
     * @memberof HotelRoomTranslationDto
     */
    'language': HotelRoomTranslationDtoLanguageEnum;
    /**
     * Translated name of the room
     * @type {string}
     * @memberof HotelRoomTranslationDto
     */
    'name': string;
}

/**
    * @export
    * @enum {string}
    */
export enum HotelRoomTranslationDtoLanguageEnum {
    En = 'EN',
    Vi = 'VI'
}


