/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Booking } from './booking';
// May contain unused imports in some cases
// @ts-ignore
import type { ProvinceTranslationsInner } from './province-translations-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCount } from './user-count';

/**
 * 
 * @export
 * @interface HotelRoom
 */
export interface HotelRoom {
    /**
     * 
     * @type {string}
     * @memberof HotelRoom
     */
    'id': string;
    /**
     * Soft delete flag
     * @type {boolean}
     * @memberof HotelRoom
     */
    'isDeleted': boolean;
    /**
     * Soft delete timestamp
     * @type {string}
     * @memberof HotelRoom
     */
    'deletedAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof HotelRoom
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof HotelRoom
     */
    'updatedAt': string;
    /**
     * Hotel Room\'s name
     * @type {string}
     * @memberof HotelRoom
     */
    'name': string;
    /**
     * Hotel Room\'s slug
     * @type {string}
     * @memberof HotelRoom
     */
    'slug': string;
    /**
     * Hotel Room\'s status
     * @type {string}
     * @memberof HotelRoom
     */
    'status': HotelRoomStatusEnum;
    /**
     * ID of the room detail
     * @type {string}
     * @memberof HotelRoom
     */
    'detailId': string;
    /**
     * List of translations for the hotel room
     * @type {Array<ProvinceTranslationsInner>}
     * @memberof HotelRoom
     */
    'translations': Array<ProvinceTranslationsInner>;
    /**
     * List of bookings
     * @type {Array<Booking>}
     * @memberof HotelRoom
     */
    'bookings'?: Array<Booking>;
    /**
     * 
     * @type {UserCount}
     * @memberof HotelRoom
     */
    '_count'?: UserCount;
}

/**
    * @export
    * @enum {string}
    */
export enum HotelRoomStatusEnum {
    Available = 'AVAILABLE',
    Booked = 'BOOKED',
    Occupied = 'OCCUPIED',
    Maintenance = 'MAINTENANCE'
}


