/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImageUploadResponseDto
 */
export interface ImageUploadResponseDto {
    /**
     * The image\'s URL.
     * @type {string}
     * @memberof ImageUploadResponseDto
     */
    'url': string;
    /**
     * The image\'s public ID in Cloudinary.
     * @type {string}
     * @memberof ImageUploadResponseDto
     */
    'publicId': string;
}

