/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImmediateDeleteRoomsDto
 */
export interface ImmediateDeleteRoomsDto {
    /**
     * List of room ids to delete
     * @type {Array<string>}
     * @memberof ImmediateDeleteRoomsDto
     */
    'ids': Array<string>;
}

