/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OccupancyRateResponseDto
 */
export interface OccupancyRateResponseDto {
    /**
     * 
     * @type {number}
     * @memberof OccupancyRateResponseDto
     */
    'rate': number;
    /**
     * 
     * @type {number}
     * @memberof OccupancyRateResponseDto
     */
    'totalRooms': number;
    /**
     * 
     * @type {number}
     * @memberof OccupancyRateResponseDto
     */
    'occupiedRooms': number;
    /**
     * 
     * @type {object}
     * @memberof OccupancyRateResponseDto
     */
    'byRoomType': object;
}

