/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaymentItemDto
 */
export interface PaymentItemDto {
    /**
     * 
     * @type {string}
     * @memberof PaymentItemDto
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof PaymentItemDto
     */
    'quantity': number;
    /**
     * 
     * @type {number}
     * @memberof PaymentItemDto
     */
    'price': number;
}

