/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PromotionTranslation
 */
export interface PromotionTranslation {
    /**
     * Unique identifier for the translation
     * @type {string}
     * @memberof PromotionTranslation
     */
    'id': string;
    /**
     * ID of the room promotion this translation belongs to
     * @type {string}
     * @memberof PromotionTranslation
     */
    'roomPromotionId': string;
    /**
     * Language of this translation
     * @type {string}
     * @memberof PromotionTranslation
     */
    'language': PromotionTranslationLanguageEnum;
    /**
     * Translated description of the promotion
     * @type {string}
     * @memberof PromotionTranslation
     */
    'description': string;
}

/**
    * @export
    * @enum {string}
    */
export enum PromotionTranslationLanguageEnum {
    En = 'EN',
    Vi = 'VI'
}


