/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RevenueByRoomTypeDto
 */
export interface RevenueByRoomTypeDto {
    /**
     * 
     * @type {string}
     * @memberof RevenueByRoomTypeDto
     */
    'roomType': RevenueByRoomTypeDtoRoomTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof RevenueByRoomTypeDto
     */
    'revenue': number;
    /**
     * 
     * @type {number}
     * @memberof RevenueByRoomTypeDto
     */
    'bookingsCount': number;
    /**
     * 
     * @type {number}
     * @memberof RevenueByRoomTypeDto
     */
    'percentageOfTotal': number;
}

/**
    * @export
    * @enum {string}
    */
export enum RevenueByRoomTypeDtoRoomTypeEnum {
    Standard = 'STANDARD',
    Superior = 'SUPERIOR',
    Deluxe = 'DELUXE'
}


