/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export enum RoleErrorMessagesEnum {
    RoleNotFound = 'roleNotFound',
    CannotBeAdmin = 'cannotBeAdmin',
    CannotBeStaff = 'cannotBeStaff',
    CannotBeCustomer = 'cannotBeCustomer',
    InvalidRoleChange = 'invalidRoleChange'
}



