/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoomPerformanceDto
 */
export interface RoomPerformanceDto {
    /**
     * 
     * @type {string}
     * @memberof RoomPerformanceDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof RoomPerformanceDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RoomPerformanceDto
     */
    'room_type': RoomPerformanceDtoRoomTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof RoomPerformanceDto
     */
    'bookings_count': number;
    /**
     * 
     * @type {number}
     * @memberof RoomPerformanceDto
     */
    'total_revenue': number;
    /**
     * 
     * @type {number}
     * @memberof RoomPerformanceDto
     */
    'average_occupancy': number;
    /**
     * 
     * @type {number}
     * @memberof RoomPerformanceDto
     */
    'cancellation_rate': number;
}

/**
    * @export
    * @enum {string}
    */
export enum RoomPerformanceDtoRoomTypeEnum {
    Standard = 'STANDARD',
    Superior = 'SUPERIOR',
    Deluxe = 'DELUXE'
}


