/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Amenity } from './amenity';
// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';
// May contain unused imports in some cases
// @ts-ignore
import type { RoomPriceHistory } from './room-price-history';
// May contain unused imports in some cases
// @ts-ignore
import type { RoomPriceHistoryTranslationsInner } from './room-price-history-translations-inner';

/**
 * 
 * @export
 * @interface RoomDetail
 */
export interface RoomDetail {
    /**
     * 
     * @type {string}
     * @memberof RoomDetail
     */
    'id': string;
    /**
     * Soft delete flag
     * @type {boolean}
     * @memberof RoomDetail
     */
    'isDeleted': boolean;
    /**
     * Soft delete timestamp
     * @type {string}
     * @memberof RoomDetail
     */
    'deletedAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof RoomDetail
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof RoomDetail
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof RoomDetail
     */
    'name': string;
    /**
     * Hotel Detail\'s slug
     * @type {string}
     * @memberof RoomDetail
     */
    'slug': string;
    /**
     * ID of the branch where this room is located
     * @type {string}
     * @memberof RoomDetail
     */
    'branchId': string;
    /**
     * Hotel Room\'s thumbnail image
     * @type {Image}
     * @memberof RoomDetail
     */
    'thumbnail': Image;
    /**
     * Hotel Room\'s image gallery
     * @type {Array<Image>}
     * @memberof RoomDetail
     */
    'images': Array<Image>;
    /**
     * 
     * @type {string}
     * @memberof RoomDetail
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof RoomDetail
     */
    'room_type': RoomDetailRoomTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RoomDetail
     */
    'bed_type': RoomDetailBedTypeEnum;
    /**
     * Room area in square meters
     * @type {number}
     * @memberof RoomDetail
     */
    'area': number;
    /**
     * 
     * @type {Array<Amenity>}
     * @memberof RoomDetail
     */
    'amenities': Array<Amenity>;
    /**
     * 
     * @type {number}
     * @memberof RoomDetail
     */
    'max_adults': number;
    /**
     * 
     * @type {number}
     * @memberof RoomDetail
     */
    'max_children': number;
    /**
     * 
     * @type {number}
     * @memberof RoomDetail
     */
    'quantity': number;
    /**
     * Hotel Room\'s base price per hour
     * @type {string}
     * @memberof RoomDetail
     */
    'base_price_per_hour': string;
    /**
     * Hotel Room\'s base price per night
     * @type {string}
     * @memberof RoomDetail
     */
    'base_price_per_night': string;
    /**
     * Hotel Room\'s base price per day
     * @type {string}
     * @memberof RoomDetail
     */
    'base_price_per_day': string;
    /**
     * Whether this room is available for booking
     * @type {boolean}
     * @memberof RoomDetail
     */
    'is_available': boolean;
    /**
     * List of translations for the room detail
     * @type {Array<RoomPriceHistoryTranslationsInner>}
     * @memberof RoomDetail
     */
    'translations': Array<RoomPriceHistoryTranslationsInner>;
    /**
     * Hotel Room\'s special price per hour
     * @type {string}
     * @memberof RoomDetail
     */
    'special_price_per_hour'?: string;
    /**
     * Hotel Room\'s special price per night
     * @type {string}
     * @memberof RoomDetail
     */
    'special_price_per_night'?: string;
    /**
     * Hotel Room\'s special price per day
     * @type {string}
     * @memberof RoomDetail
     */
    'special_price_per_day'?: string;
    /**
     * Price history of this room
     * @type {Array<RoomPriceHistory>}
     * @memberof RoomDetail
     */
    'roomPriceHistories'?: Array<RoomPriceHistory>;
}

/**
    * @export
    * @enum {string}
    */
export enum RoomDetailRoomTypeEnum {
    Standard = 'STANDARD',
    Superior = 'SUPERIOR',
    Deluxe = 'DELUXE'
}
/**
    * @export
    * @enum {string}
    */
export enum RoomDetailBedTypeEnum {
    Single = 'SINGLE',
    Double = 'DOUBLE',
    Queen = 'QUEEN',
    King = 'KING'
}


