/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoomDetail } from './room-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { RoomPriceHistoryTranslationsInner } from './room-price-history-translations-inner';

/**
 * 
 * @export
 * @interface RoomPriceHistory
 */
export interface RoomPriceHistory {
    /**
     * 
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'id': string;
    /**
     * Soft delete flag
     * @type {boolean}
     * @memberof RoomPriceHistory
     */
    'isDeleted': boolean;
    /**
     * Soft delete timestamp
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'deletedAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'updatedAt': string;
    /**
     * Name of the price history
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'name': string;
    /**
     * Description of the price history
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'description': string;
    /**
     * ID of the room detail this price history belongs to
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'roomDetailId': string;
    /**
     * Price per hour for the room
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'price_per_hour': string;
    /**
     * Price per night for the room
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'price_per_night': string;
    /**
     * Price per day for the room
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'price_per_day': string;
    /**
     * Start date when this price becomes effective
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'effective_from': string;
    /**
     * End date when this price expires
     * @type {string}
     * @memberof RoomPriceHistory
     */
    'effective_to': string;
    /**
     * Whether this price is currently being applied
     * @type {boolean}
     * @memberof RoomPriceHistory
     */
    'is_applied': boolean;
    /**
     * List of translations for the price history
     * @type {Array<RoomPriceHistoryTranslationsInner>}
     * @memberof RoomPriceHistory
     */
    'translations': Array<RoomPriceHistoryTranslationsInner>;
    /**
     * The associated room detail
     * @type {RoomDetail}
     * @memberof RoomPriceHistory
     */
    'roomDetail'?: RoomDetail;
}

