/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SortAmenityDto
 */
export interface SortAmenityDto {
    /**
     * Key of Entity to sort
     * @type {string}
     * @memberof SortAmenityDto
     */
    'orderBy': string;
    /**
     * Order of sorting
     * @type {string}
     * @memberof SortAmenityDto
     */
    'order': SortAmenityDtoOrderEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SortAmenityDtoOrderEnum {
    Asc = 'asc',
    Desc = 'desc'
}


