/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BranchTranslationDto } from './branch-translation-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';
// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';
// May contain unused imports in some cases
// @ts-ignore
import type { NearBy } from './near-by';

/**
 * 
 * @export
 * @interface UpdateBranchDto
 */
export interface UpdateBranchDto {
    /**
     * ID of the province where this branch is located
     * @type {string}
     * @memberof UpdateBranchDto
     */
    'provinceId'?: string;
    /**
     * The branch\'s thumbnail image.
     * @type {Image}
     * @memberof UpdateBranchDto
     */
    'thumbnail'?: Image;
    /**
     * The branch\'s images.
     * @type {Array<Image>}
     * @memberof UpdateBranchDto
     */
    'images'?: Array<Image>;
    /**
     * The branch\'s name.
     * @type {string}
     * @memberof UpdateBranchDto
     */
    'name'?: string;
    /**
     * The branch\'s slug.
     * @type {string}
     * @memberof UpdateBranchDto
     */
    'slug'?: string;
    /**
     * The branch\'s description.
     * @type {string}
     * @memberof UpdateBranchDto
     */
    'description'?: string;
    /**
     * The branch\'s phone number.
     * @type {string}
     * @memberof UpdateBranchDto
     */
    'phone'?: string;
    /**
     * The branch\'s active status.
     * @type {boolean}
     * @memberof UpdateBranchDto
     */
    'is_active'?: boolean;
    /**
     * The branch\'s address.
     * @type {string}
     * @memberof UpdateBranchDto
     */
    'address'?: string;
    /**
     * The branch\'s geographical location.
     * @type {Location}
     * @memberof UpdateBranchDto
     */
    'location'?: Location;
    /**
     * The branch\'s rating.
     * @type {number}
     * @memberof UpdateBranchDto
     */
    'rating'?: number;
    /**
     * Translations for the branch
     * @type {Array<BranchTranslationDto>}
     * @memberof UpdateBranchDto
     */
    'translations'?: Array<BranchTranslationDto>;
    /**
     * Branch amenities
     * @type {Array<string>}
     * @memberof UpdateBranchDto
     */
    'amenityIds'?: Array<string>;
    /**
     * Nearby locations
     * @type {Array<NearBy>}
     * @memberof UpdateBranchDto
     */
    'nearBy'?: Array<NearBy>;
}

