/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Branch } from './branch';
// May contain unused imports in some cases
// @ts-ignore
import type { Image } from './image';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCount } from './user-count';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id': string;
    /**
     * Soft delete flag
     * @type {boolean}
     * @memberof User
     */
    'isDeleted': boolean;
    /**
     * Soft delete timestamp
     * @type {string}
     * @memberof User
     */
    'deletedAt': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phone': string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'verified_email': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'verified_phone': boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'identifier_type': UserIdentifierTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'is_blocked': boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'role': UserRoleEnum;
    /**
     * The user birth date
     * @type {string}
     * @memberof User
     */
    'birth_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'gender'?: UserGenderEnum;
    /**
     * User avatar
     * @type {Image}
     * @memberof User
     */
    'avatar'?: Image;
    /**
     * Branch details where user works
     * @type {Branch}
     * @memberof User
     */
    'working_at'?: Branch;
    /**
     * 
     * @type {UserCount}
     * @memberof User
     */
    '_count'?: UserCount;
}

/**
    * @export
    * @enum {string}
    */
export enum UserIdentifierTypeEnum {
    Email = 'EMAIL',
    Phone = 'PHONE'
}
/**
    * @export
    * @enum {string}
    */
export enum UserRoleEnum {
    User = 'USER',
    Staff = 'STAFF',
    Admin = 'ADMIN'
}
/**
    * @export
    * @enum {string}
    */
export enum UserGenderEnum {
    Male = 'MALE',
    Female = 'FEMALE'
}


