/* tslint:disable */
/* eslint-disable */
/**
 * AHomeVilla documentation
 * This is AHomeVilla\'s APIs description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VerifyEmailDto
 */
export interface VerifyEmailDto {
    /**
     * User ID
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'userId': string;
    /**
     * Verification code sent to email
     * @type {string}
     * @memberof VerifyEmailDto
     */
    'code': string;
}

